"
" Load Vundle and plugins
"
source ~/bin/dotfiles/vim/plugins
source ~/bin/dotfiles/vim/statusline

let mapleader=" "
syntax on
filetype plugin indent on
colorscheme monokai

set laststatus=2
set number
set ignorecase
set hlsearch
set autoindent
set fileencoding=utf-8
set encoding=utf-8
set backspace=indent,eol,start
set smartcase
set incsearch
set showmatch
set clipboard^=unnamed
set ttimeoutlen=50
set virtualedit=onemore
set hlsearch
set cursorline
set breakindent
set noswapfile
set lazyredraw

" ZSH
" set shell=/usr/local/bin/zsh\ -i

"
" Global indent and backspace by specified # of spaces
" Check ftplugin directory for specific indentation settings
"
set expandtab
set shiftwidth=4
set softtabstop=4

" Remove trailing space
autocmd BufWritePre * :%s/\s\+$//e
set wrap
set linebreak

" CtrlP ignore files
let g:ctrlp_user_command = 'ag %s -i --nocolor --nogroup --hidden
      \ --ignore .git
      \ --ignore .svn
      \ --ignore .hg
      \ --ignore .DS_Store
      \ --ignore "**/*.pyc"
      \ -g ""'

"
" Emmet settings
"
let g:user_emmet_settings = {
\  'html': {
\       'indentation': '    '
\   },
\  'php' : {
\    'extends' : 'html',
\    'filters' : 'c',
\  },
\  'xml' : {
\    'extends' : 'html',
\  },
\}

"
" Gist
"
let g:gist_detect_filetype = 1

" Javascript syntax libraries
" angularjs, angularui, backbone, chai, flux, jasmine, jquery, prelude, react, requirejs, sugar, underscore, vue
let g:used_javascript_libs = 'handlebars, jquery, underscore, vue'

" jQuery
au BufRead,BufNewFile jquery.*.js set ft=javascript syntax=jquery
au BufRead,BufNewFile *.vue set ft=javascript syntax=vue

"
" Netrw
"
nnoremap <leader>n :Lexplore<CR>
" Windows size in columns
let g:netrw_winsize = -40
" Use tree mode
let g:netrw_liststyle = 3
" Disable help banner
let g:netrw_banner = 0

"
" Custom keymaps
"

" Save
nnoremap <leader>s :w<CR>

" Close file
nnoremap <leader>w :q<CR>

" Move through wrapped lines
nmap j gj
nmap k gk

" ALE
let g:ale_linters = { 'javascript': ['eslint'] }

